language: csharp

install:
  - nuget install Rx-Main -OutputDirectory .

script:
  - find .
  - mcs -r:"./Rx-Core.2.2.5/lib/net45/System.Reactive.Core.dll","./Rx-Linq.2.2.5/lib/net45/System.Reactive.Linq.dll","./Rx-PlatformServices.2.2.5/lib/net45/System.Reactive.PlatformServices.dll","./Rx-Interfaces.2.2.5/lib/net45/System.Reactive.Interfaces.dll" Program.cs
  - cp ./{"./Rx-Core.2.2.5/lib/net45/System.Reactive.Core.dll","./Rx-Linq.2.2.5/lib/net45/System.Reactive.Linq.dll","./PlatformServices.2.2.5/lib/net45/System.Reactive.PlatformServices.dll","./Interfaces.2.2.5/lib/net45/System.Reactive.Interfaces.dll"} ./
  - ls -rtl
  - mono Program.exe
